### ISSUE TITLE
Have a beer with Kevin

### ISSUE THREAD

**Issue by frolic** [RichardLitt/todo#3]
I haven't seen you in ages man! Looks like you've been on quite an adventure since we last hung out :) Would be super keen to grab a drink next time you're in the area (or vice versa).

**Comment by RichardLitt** [comment]
Ahaha Yes! You're still in SF, right? How long are you there?

**Comment by frolic** [comment]
Yep! Working in SF, living in Oakland. Will be here until October-ish.

**Comment by RichardLitt** [comment]
Sweet. If I get out there (hoping to at some point), will ring.

**Comment by frolic** [comment]
Any updates on this? ;)

**Comment by RichardLitt** [comment]
I believe this can be closed; although the main requisites weren't met (2. have a beer), I am satisfied with the result (time with @holic).

**Comment by RichardLitt** [comment]
Please reopen as needed.
